[package]
name = "libnacl"
version = "0.2.0"
edition = "2021"
build="build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"

[build-dependencies]
cc = { version = "1.0.72", features = ["parallel"] }
